import { Metadata } from "next";
import "../globals.css";

import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen grid grid-cols-1 md:grid-cols-2">
          {/* Promo Section */}
          <div className="relative hidden md:block text-white p-6">
            <Image
              src="/images/lemon-friday.png"
              alt="Lemon Friday Promo"
              fill
              className="w-full h-full"
            />
          </div>

          {/* Signup Form Section */}
          <div className="bg-white flex flex-col justify-center px-4 md:px-36 py-4">
            <div className="text-center mb-10">
              <Image
                src="/logo.svg"
                alt="Adron Logo"
                width={120}
                height={50}
                className="mx-auto"
              />
              <h1 className="text-xl font-semibold mt-6">
                Welcome to Adron Homes
              </h1>
              <p className="text-sm text-gray-600 mt-1">
                Referred by <strong>Mamoosh Dwayn</strong>
              </p>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
